/* QuizArena question bank */
window.QUESTION_BANK = [
  { q: "What is a system?", options: { A: "A random collection of data", B: "An organized collection of components working together to achieve goals", C: "A programming language", D: "A database only" }, answer: "B" },
  { q: "Which of the following is an example of an input in a system?", options: { A: "Reports", B: "Customer feedback", C: "Raw data", D: "Finished products" }, answer: "C" },
  { q: "Which component transforms inputs into outputs?", options: { A: "Feedback", B: "Process", C: "Boundary", D: "Environment" }, answer: "B" },
  { q: "What is feedback in a system?", options: { A: "Final product of a system", B: "Information used to improve the system", C: "External environment", D: "Raw material" }, answer: "B" },
  { q: "Which type of system interacts with its environment?", options: { A: "Closed system", B: "Isolated system", C: "Open system", D: "Static system" }, answer: "C" },
  { q: "Which of the following is NOT a component of an information system?", options: { A: "Hardware", B: "Networks", C: "Furniture", D: "Software" }, answer: "C" },
  { q: "The SDLC stands for:", options: { A: "Software Data Logic Control", B: "System Development Life Cycle", C: "Structured Design Level Cycle", D: "System Database Lifecycle Control" }, answer: "B" },
  { q: "Which phase of SDLC focuses on gathering detailed requirements?", options: { A: "Deployment", B: "Testing", C: "Analysis", D: "Maintenance" }, answer: "C" },
  { q: "Which SDLC phase involves coding the system?", options: { A: "Design", B: "Implementation", C: "Analysis", D: "Planning" }, answer: "B" },
  { q: "Which deliverable is produced during the planning phase?", options: { A: "Source code", B: "Test scripts", C: "Project charter", D: "Database schema" }, answer: "C" },
  { q: "Which SDLC model is linear and sequential?", options: { A: "Agile", B: "Spiral", C: "Iterative", D: "Waterfall" }, answer: "D" },
  { q: "Which SDLC model uses sprints?", options: { A: "V-Model", B: "Agile", C: "Waterfall", D: "Spiral" }, answer: "B" },
  { q: "Which SDLC model focuses heavily on risk assessment?", options: { A: "Spiral Model", B: "Agile Model", C: "Waterfall Model", D: "V-Model" }, answer: "A" },
  { q: "A system analyst mainly acts as a bridge between:", options: { A: "Customers and suppliers", B: "Business problems and technology solutions", C: "Hardware and electricity", D: "Data and networks" }, answer: "B" },
  { q: "Which of the following is a role of a system analyst?", options: { A: "Cooking data", B: "Requirement gathering", C: "Selling products", D: "Manufacturing devices" }, answer: "B" },
  { q: "Which skill helps a system analyst evaluate different solutions?", options: { A: "Cooking skill", B: "Critical thinking", C: "Singing skill", D: "Typing speed" }, answer: "B" },
  { q: "Which tool is commonly used in system design?", options: { A: "Photoshop", B: "UML", C: "TikTok", D: "VLC" }, answer: "B" },
  { q: "Business system analysts mainly focus on:", options: { A: "Hardware repairs", B: "Bridging business needs and IT solutions", C: "Selling devices", D: "Cooking food" }, answer: "B" },
  { q: "Technical system analysts focus more on:", options: { A: "Marketing", B: "Technical architecture and integration", C: "Customer service", D: "Sales strategy" }, answer: "B" },
  { q: "Data analysts primarily deal with:", options: { A: "Cooking ingredients", B: "Analyzing data to support decisions", C: "Designing buildings", D: "Composing music" }, answer: "B" },
  { q: "Which is a soft skill important for system analysts?", options: { A: "Communication", B: "Welding", C: "Driving", D: "Painting" }, answer: "A" },
  { q: "Which is a technical skill required for system analysts?", options: { A: "Knowledge of programming and databases", B: "Cooking recipes", C: "Sports training", D: "Music composition" }, answer: "A" },
  { q: "Stakeholders in a project are:", options: { A: "Only developers", B: "People who have an interest in the project", C: "Only managers", D: "External hackers" }, answer: "B" },
  { q: "Which is an example of an internal stakeholder?", options: { A: "Customer", B: "Government", C: "Employee", D: "Supplier" }, answer: "C" },
  { q: "Which is an example of an external stakeholder?", options: { A: "Project manager", B: "Customer", C: "Developer", D: "Tester" }, answer: "B" },
  { q: "Why is stakeholder identification important?", options: { A: "To ignore them", B: "To understand requirements and expectations", C: "To delay the project", D: "To remove their input" }, answer: "B" },
  { q: "Interviews are useful in requirements gathering because:", options: { A: "They allow detailed personal input", B: "They are always anonymous", C: "They cost nothing", D: "They avoid stakeholders" }, answer: "A" },
  { q: "Questionnaires are best used when:", options: { A: "Few people are involved", B: "Large groups need to be surveyed", C: "Stakeholders are unavailable", D: "Detailed personal info is required" }, answer: "B" },
  { q: "A limitation of questionnaires?", options: { A: "Time consuming", B: "No standardized responses", C: "Limited depth of information", D: "Requires workshops" }, answer: "C" },
  { q: "Workshops and brainstorming sessions are useful for:", options: { A: "Isolating stakeholders", B: "Generating ideas collaboratively", C: "Coding software", D: "Deleting requirements" }, answer: "B" },
  { q: "Observation and shadowing help analysts identify:", options: { A: "Music preferences", B: "Pain points and inefficiencies", C: "Salary structures", D: "Coding errors only" }, answer: "B" },
  { q: "Functional requirements describe:", options: { A: "System appearance only", B: "What the system should do", C: "Staff salaries", D: "Hardware brands" }, answer: "B" },
  { q: "Which is an example of a non-functional requirement?", options: { A: "Generate reports", B: "Track customer interactions", C: "System must support mobile access", D: "Process payments" }, answer: "C" },
  { q: "Requirements analysis involves:", options: { A: "Ignoring stakeholders", B: "Studying stakeholder needs and constraints", C: "Deleting old systems", D: "Coding immediately" }, answer: "B" },
  { q: "Which step verifies requirements with stakeholders?", options: { A: "Coding", B: "Validation", C: "Deployment", D: "Maintenance" }, answer: "B" },
  { q: "Requirements prioritization is based on:", options: { A: "Developer mood", B: "Importance and feasibility", C: "Random selection", D: "Budget alone" }, answer: "B" },
  { q: "Traceability in requirements means:", options: { A: "Tracking employees", B: "Linking requirements with SDLC artifacts", C: "Tracing hackers", D: "Connecting cables" }, answer: "B" },
  { q: "A requirements document should be:", options: { A: "Ambiguous", B: "Long and confusing", C: "Clear and concise", D: "Unstructured" }, answer: "C" },
  { q: "Which section is commonly included in requirements documentation?", options: { A: "Sports analysis", B: "Functional requirements", C: "Music playlist", D: "Weather report" }, answer: "B" },
  { q: "One importance of requirements documentation is:", options: { A: "Increasing ambiguity", B: "Guiding design and development", C: "Preventing communication", D: "Reducing stakeholders" }, answer: "B" },
];
